apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: shank-cluster
  region: ap-south-1

nodeGroups:
   - name: ng1
     desiredCapacity: 2
     instanceType: t2.micro
     ssh:
        publicKeyName: newkey