apiVersion: v1
kind: Pod
metadata:
  name: myjenkins
  labels:
    app: jenkins
spec:
  containers:
  - name: myjenkins-con
    image: shanky25/jenkins_kube:v1
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
spec:
  type: LoadBalancer
  selector:
    app: jenkins
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 8080
      targetPort: 8080
      # Optional field
      nodePort: 30001




